"""
dashboard.py
============
Interactive Streamlit dashboard for the Loblaw Bio cell-count analysis.

Run from the repository root with::

    streamlit run dashboard.py

Reads pre-computed outputs from ``outputs/`` (generated by ``pipeline.py``) and
queries ``teiko.db`` live for the raw-data and subset-explorer views. All paths
are relative so it works in Codespaces / Streamlit Community Cloud.
"""

import os
import sqlite3

import pandas as pd
import streamlit as st

ROOT = os.path.dirname(os.path.abspath(__file__))
DB_PATH = os.path.join(ROOT, "teiko.db")
OUT_DIR = os.path.join(ROOT, "outputs")
TABLES_DIR = os.path.join(OUT_DIR, "tables")
PLOTS_DIR = os.path.join(OUT_DIR, "plots")

POPULATIONS = ["b_cell", "cd8_t_cell", "cd4_t_cell", "nk_cell", "monocyte"]

# --- Theme ----------------------------------------------------------------
st.set_page_config(
    page_title="Loblaw Bio — Cell Count Dashboard",
    layout="wide",
    initial_sidebar_state="expanded",
)

ACCENT = "#2ca58d"
ACCENT2 = "#d1495b"

st.markdown(
    f"""
    <style>
    .stApp {{ background-color: #0e1117; color: #fafafa; }}
    section[data-testid="stSidebar"] {{ background-color: #161a23; }}
    h1, h2, h3 {{ color: {ACCENT}; }}
    div[data-testid="stMetricValue"] {{ color: {ACCENT}; }}
    </style>
    """,
    unsafe_allow_html=True,
)


# --- Data access ----------------------------------------------------------
@st.cache_data
def load_frequencies():
    path = os.path.join(TABLES_DIR, "cell_frequencies.csv")
    return pd.read_csv(path) if os.path.exists(path) else pd.DataFrame()


@st.cache_data
def load_statistics():
    path = os.path.join(TABLES_DIR, "statistical_results.csv")
    return pd.read_csv(path) if os.path.exists(path) else pd.DataFrame()


@st.cache_data
def load_subset():
    path = os.path.join(TABLES_DIR, "subset_analysis.csv")
    return pd.read_csv(path) if os.path.exists(path) else pd.DataFrame()


@st.cache_data
def load_full_table():
    """Flat join of the whole database for the raw-data view."""
    conn = sqlite3.connect(DB_PATH)
    try:
        df = pd.read_sql_query(
            """
            SELECT subj.project_id AS project, subj.subject_id AS subject,
                   subj.condition, subj.age, subj.sex, subj.treatment,
                   subj.response, s.sample_id AS sample, s.sample_type,
                   s.time_from_treatment_start,
                   cc.b_cell, cc.cd8_t_cell, cc.cd4_t_cell, cc.nk_cell,
                   cc.monocyte
            FROM samples s
            JOIN subjects subj  ON s.subject_id = subj.subject_id
            JOIN cell_counts cc ON cc.sample_id = s.sample_id
            ORDER BY s.sample_id
            """,
            conn,
        )
    finally:
        conn.close()
    return df


def query_subset(condition, treatment, timepoint):
    """Live DB query for the interactive subset explorer."""
    conn = sqlite3.connect(DB_PATH)
    try:
        df = pd.read_sql_query(
            """
            SELECT subj.project_id AS project, subj.subject_id AS subject,
                   subj.sex, subj.response, s.sample_id AS sample,
                   s.time_from_treatment_start, cc.b_cell
            FROM samples s
            JOIN subjects subj  ON s.subject_id = subj.subject_id
            JOIN cell_counts cc ON cc.sample_id = s.sample_id
            WHERE subj.condition = ?
              AND subj.treatment = ?
              AND s.sample_type = 'PBMC'
              AND s.time_from_treatment_start = ?
            """,
            conn,
            params=(condition, treatment, timepoint),
        )
    finally:
        conn.close()
    return df


if not os.path.exists(DB_PATH):
    st.error("teiko.db not found. Run `python load_data.py` and "
             "`python pipeline.py` first (or `make pipeline`).")
    st.stop()

full_df = load_full_table()
freq_df = load_frequencies()
stats_df = load_statistics()
subset_df = load_subset()

# --- Sidebar filters ------------------------------------------------------
st.sidebar.title("Filters")


def _multi(label, col):
    options = sorted(x for x in full_df[col].dropna().unique())
    chosen = st.sidebar.multiselect(label, options, default=[])
    return options if not chosen else chosen


cond_sel = _multi("Condition", "condition")
treat_sel = _multi("Treatment", "treatment")
type_sel = _multi("Sample type", "sample_type")

resp_options = sorted(x for x in full_df["response"].dropna().unique())
resp_chosen = st.sidebar.multiselect("Response", resp_options, default=[])

mask = (
    full_df["condition"].isin(cond_sel)
    & full_df["treatment"].isin(treat_sel)
    & full_df["sample_type"].isin(type_sel)
)
if resp_chosen:
    mask &= full_df["response"].isin(resp_chosen)
filtered_df = full_df[mask]

st.sidebar.markdown("---")
st.sidebar.caption(f"{len(filtered_df):,} of {len(full_df):,} samples selected")

# --- Header ---------------------------------------------------------------
st.title("Loblaw Bio — Immune Cell Population Dashboard")
st.caption("Clinical trial analysis of miraclib response in melanoma patients")

tab1, tab2, tab3, tab4 = st.tabs(
    ["Data Overview", "Statistical Analysis", "Subset Explorer", "Raw Data"]
)

# =========================================================================
# Tab 1 — Data Overview
# =========================================================================
with tab1:
    st.header("Data Overview")

    c1, c2, c3 = st.columns(3)
    c1.metric("Total samples", f"{filtered_df['sample'].nunique():,}")
    c2.metric("Total subjects", f"{filtered_df['subject'].nunique():,}")
    c3.metric("Projects", f"{filtered_df['project'].nunique():,}")

    st.subheader("Per-sample cell population frequencies")
    if freq_df.empty:
        st.info("Run the pipeline to generate the frequency table.")
    else:
        # Restrict the frequency table to the samples passing the sidebar filter.
        view = freq_df[freq_df["sample"].isin(filtered_df["sample"])]
        st.dataframe(view, use_container_width=True, height=350)

        st.subheader("Mean relative frequency per cell type (selected samples)")
        means = (
            view.groupby("population")["percentage"].mean()
            .reindex(POPULATIONS)
        )
        st.bar_chart(means, color=ACCENT, height=350)

# =========================================================================
# Tab 2 — Statistical Analysis
# =========================================================================
with tab2:
    st.header("Responders vs Non-Responders")
    st.caption("Cohort: melanoma + miraclib + PBMC samples "
               "(two-sided Mann-Whitney U test)")

    if stats_df.empty:
        st.info("Run the pipeline to generate statistical results.")
    else:
        def _highlight(row):
            color = "background-color: #14432a" if row["significant"] else ""
            return [color] * len(row)

        st.dataframe(
            stats_df.style.apply(_highlight, axis=1).format(
                {"mean_responders": "{:.4f}",
                 "mean_non_responders": "{:.4f}",
                 "p_value": "{:.4g}"}
            ),
            use_container_width=True,
        )

        sig = stats_df[stats_df["significant"]]["population"].tolist()
        if sig:
            st.success(
                "Significantly different populations (p < 0.05): "
                + ", ".join(sig)
            )
        else:
            st.warning("No populations reached significance at p < 0.05.")

        st.subheader("Boxplot")
        img = os.path.join(PLOTS_DIR, "boxplot_cell_populations.png")
        if os.path.exists(img):
            st.image(img, use_container_width=True)
        else:
            st.info("Boxplot not found — run the pipeline.")

# =========================================================================
# Tab 3 — Subset Explorer
# =========================================================================
with tab3:
    st.header("Baseline Subset Explorer")

    st.subheader("Pre-computed baseline subset (melanoma · miraclib · time=0)")
    if subset_df.empty:
        st.info("Run the pipeline to generate the subset analysis.")
    else:
        st.dataframe(subset_df, use_container_width=True)

    st.markdown("---")
    st.subheader("Live query")
    col1, col2, col3 = st.columns(3)
    conditions = sorted(full_df["condition"].dropna().unique())
    treatments = sorted(full_df["treatment"].dropna().unique())
    times = sorted(int(t) for t in full_df["time_from_treatment_start"].dropna().unique())

    sel_cond = col1.selectbox(
        "Condition", conditions,
        index=conditions.index("melanoma") if "melanoma" in conditions else 0,
    )
    sel_treat = col2.selectbox(
        "Treatment", treatments,
        index=treatments.index("miraclib") if "miraclib" in treatments else 0,
    )
    sel_time = col3.selectbox("Time from treatment start", times, index=0)

    live = query_subset(sel_cond, sel_treat, sel_time)
    st.caption(f"{len(live)} PBMC samples match "
               f"({sel_cond} · {sel_treat} · time={sel_time}).")

    if not live.empty:
        m1, m2, m3 = st.columns(3)
        subj = live.drop_duplicates("subject")
        m1.metric("Samples", len(live))
        m2.metric("Responders / Non-responders",
                  f"{(subj['response'] == 'yes').sum()} / "
                  f"{(subj['response'] == 'no').sum()}")
        m3.metric("Male / Female",
                  f"{(subj['sex'] == 'M').sum()} / "
                  f"{(subj['sex'] == 'F').sum()}")

        st.subheader("Samples per project")
        per_proj = (
            live.groupby("project")["sample"].count()
            .rename("sample_count").reset_index()
        )
        pc1, pc2 = st.columns([1, 2])
        pc1.dataframe(per_proj, use_container_width=True, hide_index=True)
        pc2.bar_chart(per_proj.set_index("project")["sample_count"],
                      color=ACCENT, height=300)

        male_resp = live[(live["sex"] == "M") & (live["response"] == "yes")]
        if not male_resp.empty:
            st.metric(f"Avg B cells — {sel_cond} males, responders @ time={sel_time}",
                      f"{male_resp['b_cell'].mean():.2f}")
    else:
        st.warning("No samples match this combination.")

# =========================================================================
# Tab 4 — Raw Data
# =========================================================================
with tab4:
    st.header("Raw Data")
    st.caption("Live from teiko.db — filtered by the sidebar selection.")

    search = st.text_input("Search (matches any column)", "")
    view = filtered_df
    if search:
        s = search.lower()
        view = view[view.apply(
            lambda r: s in " ".join(map(str, r.values)).lower(), axis=1
        )]

    st.caption(f"{len(view):,} rows")
    st.dataframe(view, use_container_width=True, height=500)

    st.download_button(
        "Download CSV",
        data=view.to_csv(index=False).encode("utf-8"),
        file_name="cell_count_filtered.csv",
        mime="text/csv",
    )
